# Generated by Django 2.2.3 on 2019-07-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('country', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'holidays',
            },
        ),
    ]
